name: (prod) Deploy docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: dist
          retention-days: 3

  deployment:
    runs-on: ubuntu-latest
    needs: build
    name: deployment
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: dist

      - name: deploy prod
        uses: cloudflare/wrangler-action@1.3.0
        env:
          USER: root
        with:
          apiToken: ${{ secrets.cf_api_token }}
          environment: prod
